### ISSUE TITLE
Update Monitor Implementation

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime#129]
Update the implementation in a way that the Spring-Framework is utilized as supposed to be.

## ToDo's

- [ ] Replace CLI arguments with application profiles and environment variables
    - Profiles: develop, lab, deploy
    - default profile is develop
- [ ] Use Beans to access these arguments
- [ ] Update the GitHub workflows to use the `deploy` profile for building jar
